language: c++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-4.9
      - g++-4.9
matrix:
  include:
     - env: TRAVIS_CC=gcc-4.9 TRAVIS_CXX=g++-4.9
before_install:
  export CC=$TRAVIS_CC
  export CXX=$TRAVIS_CXX
script:
  - ./bootstrap.sh
  - PATH="$(pwd)/bin:$PATH" make check
  - PATH="$(pwd)/bin:$PATH" ptest --verbose
