language: c++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-4.8
      - g++-4.8
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
matrix:
  include:
     - env: TRAVIS_CC=gcc-4.8 TRAVIS_CXX=g++-4.8
     - env: TRAVIS_CC=gcc-4.9 TRAVIS_CXX=g++-4.9
     - env: TRAVIS_CC=gcc-5   TRAVIS_CXX=g++-5
     - env: TRAVIS_CC=gcc-6   TRAVIS_CXX=g++-6
before_install:
  export CC=$TRAVIS_CC
  export CXX=$TRAVIS_CXX
script:
  - ./bootstrap.sh
  - PATH="$(pwd)/bin:$PATH" make check
  - PATH="$(pwd)/bin:$PATH" ptest --verbose
